### PR TITLE
Update gtk-lshw.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
add FR and ES comments. FR is mine and ES is taken from the Debian version of the .desktop file : http://sources.debian.net/src/lshw/02.17-1.1/debian/patches/lshw-gtk.desktop/?hl=4#L4 .
Don't know if that would be useful to you but Debian is carrying a few patches : http://sources.debian.net/src/lshw/02.17-1.1/debian/patches/ you might be happy to integrate.
Anyway, thanks for this soft!

### CODE REVIEW

**Comment by trebmuh** [comment]
ping ?

**Comment by lyonel** [comment]
please don't use Github for reporting issues, use Trac on http://ezix.org

**Comment by trebmuh** [comment]
done

**Comment by trebmuh** [comment]
Thanks for having added the FR and ES Comment in the desktop file : https://github.com/lyonel/lshw/commit/7a3d7c424750a3166625d2c1108dbc5d75e59b60 . I can now delete my fork-branch.

**Pull request closed without merging**
