### PR TITLE
Revert "Fix JSON output format"

### PR DESCRIPTION
**Pull request by nayefc**
This reverts commit 135a853c60582b14c5b67e5cd988a8062d9896f4.

### CODE REVIEW

**Comment by ycheng** [comment]
I am working on using jsoncpp to output json. Maybe we can hold on this one.

**Comment by ycheng** [comment]
some conversation happens in

https://ezix.org/src/pkg/lshw/pulls/26

**Comment by ycheng** [comment]
it's fixed, this can be closed.

**Comment by limbo127** [comment]
I'm sorry but it does not work
last git version, linux x86_64 plateforme
[
{
  "id" : "gallet",
  "class" : "system",
  "claimed" : true,
  "handle" : "DMI:0001",
  "description" : "Desktop Computer",
  "vendor" : "Intel Corporation",
  "version" : "1.0",
  "width" : 64,
  "configuration" : {
    "boot" : "normal",
    "chassis" : "desktop",
    "uuid" : "6C524C50-8DA6-834A-81BC-55C19A183190"
  },
  "capabilities" : {
    "smbios-3.0.0" : "SMBIOS version 3.0.0",
    "dmi-3.0.0" : "DMI version 3.0.0",
    "smp" : "Symmetric Multi-Processing",
    "vsyscall32" : "32-bit processes"
  }    {
      "id" : "core",
      "class" : "bus",
      "claimed" : true,
      "handle" : "DMI:0002",
      "description" : "Motherboard",
      "product" : "NUC6i7KYB",
      "vendor" : "Intel Corporation",
      "physid" : "0",
      "version" : "H90766-403",
      "serial" : "BTKY624001KA",
      "slot" : "Default string"        {
          "id" : "firmware",
          "class" : "memory",
          "claimed" : true,
          "description" : "BIOS",
          "vendor" : "American Megatrends Inc.",
          "physid" : "0",
          "version" : "KYSKLi70.86A.0034.2016.0503.1003",
          "date" : "05/03/2016",
          "units" : "bytes",
          "size" : 65536,
          "capacity" : 6291456,
          "capabilities" : {
            "pci" : "PCI bus",
            "upgrade" : "BIOS EEPROM can be upgraded",
            "shadowing" : "BIOS shadowing",
            "cdboot" : "Booting from CD-ROM/DVD",
            "bootselect" : "Selectable boot path",
            "socketedrom" : "BIOS ROM is socketed",
            "edd" : "Enhanced Disk Drive extensions",
            "int13floppy1200" : "5.25\" 1.2MB floppy",
            "int13floppy720" : "3.5\" 720KB floppy",
            "int13floppy2880" : "3.5\" 2.88MB floppy",
            "int5printscreen" : "Print Screen key",
            "int14serial" : "INT14 serial line control",
            "int17printer" : "INT17 printer control",
            "acpi" : "ACPI",
            "usb" : "USB legacy emulation",
            "biosbootspecification" : "BIOS boot specification",
            "uefi" : "UEFI specification is supported"
          }
        },
        {
          "id" : "cache:0",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:0021",
          "description" : "L1 cache",
          "physid" : "21",
          "slot" : "L1 Cache",
          "units" : "bytes",
          "size" : 131072,
          "capacity" : 131072,
          "configuration" : {
            "level" : "1"
          },
          "capabilities" : {
            "synchronous" : "Synchronous",
            "internal" : "Internal",
            "write-back" : "Write-back",
            "data" : "Data cache"
          }
        },
        {
          "id" : "cache:1",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:0022",
          "description" : "L1 cache",
          "physid" : "22",
          "slot" : "L1 Cache",
          "units" : "bytes",
          "size" : 131072,
          "capacity" : 131072,
          "configuration" : {
            "level" : "1"
          },
          "capabilities" : {
            "synchronous" : "Synchronous",
            "internal" : "Internal",
            "write-back" : "Write-back",
            "instruction" : "Instruction cache"
          }
        },
        {
          "id" : "cache:2",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:0023",
          "description" : "L2 cache",
          "physid" : "23",
          "slot" : "L2 Cache",
          "units" : "bytes",
          "size" : 1048576,
          "capacity" : 1048576,
          "configuration" : {
            "level" : "2"
          },
          "capabilities" : {
            "synchronous" : "Synchronous",
            "internal" : "Internal",
            "write-back" : "Write-back",
            "unified" : "Unified cache"
          }
        },
        {
          "id" : "cache:3",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:0024",
          "description" : "L3 cache",
          "physid" : "24",
          "slot" : "L3 Cache",
          "units" : "bytes",
          "size" : 6291456,
          "capacity" : 6291456,
          "configuration" : {
            "level" : "3"
          },
          "capabilities" : {
            "synchronous" : "Synchronous",
            "internal" : "Internal",
            "write-back" : "Write-back",
            "unified" : "Unified cache"
          }
        },
        {
          "id" : "cpu",
          "class" : "processor",
          "claimed" : true,
          "handle" : "DMI:0025",
          "description" : "CPU",
          "product" : "Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz",
          "vendor" : "Intel Corp.",
          "physid" : "25",
          "businfo" : "cpu@0",
          "version" : "Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz",
          "serial" : "To Be Filled By O.E.M.",
          "slot" : "U3E1",
          "units" : "Hz",
          "size" : 3403840000,
          "capacity" : 4005032704,
          "width" : 64,
          "clock" : 100000000,
          "configuration" : {
            "cores" : "4",
            "enabledcores" : "4",
            "threads" : "8"
          },
          "capabilities" : {
            "lm" : "64bits extensions (x86-64)",
            "fpu" : "mathematical co-processor",
            "fpu_exception" : "FPU exceptions reporting",
            "wp" : true,
            "vme" : "virtual mode extensions",
            "de" : "debugging extensions",
            "pse" : "page size extensions",
            "tsc" : "time stamp counter",
            "msr" : "model-specific registers",
            "pae" : "4GB+ memory addressing (Physical Address Extension)",
            "mce" : "machine check exceptions",
            "cx8" : "compare and exchange 8-byte",
            "apic" : "on-chip advanced programmable interrupt controller (APIC)",
            "sep" : "fast system calls",
            "mtrr" : "memory type range registers",
            "pge" : "page global enable",
            "mca" : "machine check architecture",
            "cmov" : "conditional move instruction",
            "pat" : "page attribute table",
            "pse36" : "36-bit page size extensions",
            "clflush" : true,
            "dts" : "debug trace and EMON store MSRs",
            "acpi" : "thermal control (ACPI)",
            "mmx" : "multimedia extensions (MMX)",
            "fxsr" : "fast floating point save/restore",
            "sse" : "streaming SIMD extensions (SSE)",
            "sse2" : "streaming SIMD extensions (SSE2)",
            "ss" : "self-snoop",
            "ht" : "HyperThreading",
            "tm" : "thermal interrupt and status",
            "pbe" : "pending break event",
            "syscall" : "fast system calls",
            "nx" : "no-execute bit (NX)",
            "pdpe1gb" : true,
            "rdtscp" : true,
            "x86-64" : "64bits extensions (x86-64)",
            "constant_tsc" : true,
            "art" : true,
            "arch_perfmon" : true,
            "pebs" : true,
            "bts" : true,
            "rep_good" : true,
            "nopl" : true,
            "xtopology" : true,
            "nonstop_tsc" : true,
            "cpuid" : true,
            "aperfmperf" : true,
            "pni" : true,
            "pclmulqdq" : true,
            "dtes64" : true,
            "monitor" : true,
            "ds_cpl" : true,
            "vmx" : true,
            "est" : true,
            "tm2" : true,
            "ssse3" : true,
            "sdbg" : true,
            "fma" : true,
            "cx16" : true,
            "xtpr" : true,
            "pdcm" : true,
            "pcid" : true,
            "sse4_1" : true,
            "sse4_2" : true,
            "x2apic" : true,
            "movbe" : true,
            "popcnt" : true,
            "tsc_deadline_timer" : true,
            "aes" : true,
            "xsave" : true,
            "avx" : true,
            "f16c" : true,
            "rdrand" : true,
            "lahf_lm" : true,
            "abm" : true,
            "3dnowprefetch" : true,
            "cpuid_fault" : true,
            "epb" : true,
            "invpcid_single" : true,
            "pti" : true,
            "ssbd" : true,
            "ibrs" : true,
            "ibpb" : true,
            "stibp" : true,
            "tpr_shadow" : true,
            "vnmi" : true,
            "flexpriority" : true,
            "ept" : true,
            "vpid" : true,
            "ept_ad" : true,
            "fsgsbase" : true,
            "tsc_adjust" : true,
            "bmi1" : true,
            "hle" : true,
            "avx2" : true,
            "smep" : true,
            "bmi2" : true,
            "erms" : true,
            "invpcid" : true,
            "rtm" : true,
            "mpx" : true,
            "rdseed" : true,
            "adx" : true,
            "smap" : true,
            "clflushopt" : true,
            "intel_pt" : true,
            "xsaveopt" : true,
            "xsavec" : true,
            "xgetbv1" : true,
            "xsaves" : true,
            "dtherm" : true,
            "ida" : true,
            "arat" : true,
            "pln" : true,
            "pts" : true,
            "hwp" : true,
            "hwp_notify" : true,
            "hwp_act_window" : true,
            "hwp_epp" : true,
            "md_clear" : true,
            "flush_l1d" : true,
            "cpufreq" : "CPU Frequency scaling"
          }
        },
        {
          "id" : "memory",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:0026",
          "description" : "System Memory",
          "physid" : "26",
          "slot" : "System board or motherboard",
          "units" : "bytes",
          "size" : 12884901888            {
              "id" : "bank:0",
              "class" : "memory",
              "claimed" : true,
              "handle" : "DMI:0027",
              "description" : "SODIMM DDR4 Synchronous 2133 MHz (0,5 ns)",
              "product" : "CT4G4SFS8213.C8FBR2",
              "vendor" : "Conexant (Rockwell)",
              "physid" : "0",
              "serial" : "16292420",
              "slot" : "ChannelA-DIMM0",
              "units" : "bytes",
              "size" : 4294967296,
              "width" : 64,
              "clock" : 2133000000
            },
            {
              "id" : "bank:1",
              "class" : "memory",
              "claimed" : true,
              "handle" : "DMI:0028",
              "description" : "SODIMM DDR4 Synchronous 2133 MHz (0,5 ns)",
              "product" : "CT8G4SFS824A.M8FE",
              "vendor" : "Conexant (Rockwell)",
              "physid" : "1",
              "serial" : "34203920",
              "slot" : "ChannelB-DIMM0",
              "units" : "bytes",
              "size" : 8589934592,
              "width" : 64,
              "clock" : 2133000000
            },

        },
        {
          "id" : "pci",
          "class" : "bridge",
          "claimed" : true,
          "handle" : "PCIBUS:0000:00",
          "description" : "Host bridge",
          "product" : "Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers",
          "vendor" : "Intel Corporation",
          "physid" : "100",
          "businfo" : "pci@0000:00:00.0",
          "version" : "0a",
          "width" : 32,
          "clock" : 33000000,
          "configuration" : {
            "driver" : "skl_uncore"
          }            {
              "id" : "display",
              "class" : "display",
              "claimed" : true,
              "handle" : "PCI:0000:00:02.0",
              "description" : "VGA compatible controller",
              "product" : "Iris Pro Graphics 580",
              "vendor" : "Intel Corporation",
              "physid" : "2",
              "businfo" : "pci@0000:00:02.0",
              "version" : "09",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "i915",
                "latency" : "0"
              },
              "capabilities" : {
                "pciexpress" : "PCI Express",
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "vga_controller" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing",
                "rom" : "extension ROM"
              }
            },
            {
              "id" : "generic:0",
              "class" : "generic",
              "handle" : "PCI:0000:00:08.0",
              "description" : "System peripheral",
              "product" : "Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model",
              "vendor" : "Intel Corporation",
              "physid" : "8",
              "businfo" : "pci@0000:00:08.0",
              "version" : "00",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "latency" : "0"
              },
              "capabilities" : {
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "usb",
              "class" : "bus",
              "claimed" : true,
              "handle" : "PCI:0000:00:14.0",
              "description" : "USB controller",
              "product" : "100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller",
              "vendor" : "Intel Corporation",
              "physid" : "14",
              "businfo" : "pci@0000:00:14.0",
              "version" : "31",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "xhci_hcd",
                "latency" : "0"
              },
              "capabilities" : {
                "pm" : "Power Management",
                "msi" : "Message Signalled Interrupts",
                "xhci" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }                {
                  "id" : "usbhost:0",
                  "class" : "bus",
                  "claimed" : true,
                  "handle" : "USB:1:1",
                  "product" : "xHCI Host Controller",
                  "vendor" : "Linux 5.3.0-59-generic xhci-hcd",
                  "physid" : "0",
                  "businfo" : "usb@1",
                  "logicalname" : "usb1",
                  "version" : "5.03",
                  "configuration" : {
                    "driver" : "hub",
                    "slots" : "16",
                    "speed" : "480Mbit/s"
                  },
                  "capabilities" : {
                    "usb-2.00" : "USB 2.0"
                  }                    {
                      "id" : "usb:0",
                      "class" : "input",
                      "claimed" : true,
                      "handle" : "USB:1:2",
                      "description" : "Keyboard",
                      "product" : "USB Receiver",
                      "vendor" : "Logitech",
                      "physid" : "4",
                      "businfo" : "usb@1:4",
                      "version" : "12.11",
                      "configuration" : {
                        "driver" : "usbhid",
                        "maxpower" : "98mA",
                        "speed" : "12Mbit/s"
                      },
                      "capabilities" : {
                        "usb-2.00" : "USB 2.0"
                      }
                    },
                    {
                      "id" : "usb:1",
                      "class" : "communication",
                      "claimed" : true,
                      "handle" : "USB:1:3",
                      "description" : "Bluetooth wireless interface",
                      "vendor" : "Intel Corp.",
                      "physid" : "9",
                      "businfo" : "usb@1:9",
                      "version" : "0.01",
                      "configuration" : {
                        "driver" : "btusb",
                        "maxpower" : "100mA",
                        "speed" : "12Mbit/s"
                      },
                      "capabilities" : {
                        "bluetooth" : "Bluetooth wireless radio",
                        "usb-2.00" : "USB 2.0"
                      }
                    },

                },
                {
                  "id" : "usbhost:1",
                  "class" : "bus",
                  "claimed" : true,
                  "handle" : "USB:2:1",
                  "product" : "xHCI Host Controller",
                  "vendor" : "Linux 5.3.0-59-generic xhci-hcd",
                  "physid" : "1",
                  "businfo" : "usb@2",
                  "logicalname" : "usb2",
                  "version" : "5.03",
                  "configuration" : {
                    "driver" : "hub",
                    "slots" : "8",
                    "speed" : "5000Mbit/s"
                  },
                  "capabilities" : {
                    "usb-3.00" : true
                  }
                },

            },
            {
              "id" : "generic:1",
              "class" : "generic",
              "claimed" : true,
              "handle" : "PCI:0000:00:14.2",
              "description" : "Signal processing controller",
              "product" : "100 Series/C230 Series Chipset Family Thermal Subsystem",
              "vendor" : "Intel Corporation",
              "physid" : "14.2",
              "businfo" : "pci@0000:00:14.2",
              "version" : "31",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "intel_pch_thermal",
                "latency" : "0"
              },
              "capabilities" : {
                "pm" : "Power Management",
                "msi" : "Message Signalled Interrupts",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "communication",
              "class" : "communication",
              "claimed" : true,
              "handle" : "PCI:0000:00:16.0",
              "description" : "Communication controller",
              "product" : "100 Series/C230 Series Chipset Family MEI Controller #1",
              "vendor" : "Intel Corporation",
              "physid" : "16",
              "businfo" : "pci@0000:00:16.0",
              "version" : "31",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "mei_me",
                "latency" : "0"
              },
              "capabilities" : {
                "pm" : "Power Management",
                "msi" : "Message Signalled Interrupts",
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "sata",
              "class" : "storage",
              "claimed" : true,
              "handle" : "PCI:0000:00:17.0",
              "description" : "SATA controller",
              "product" : "HM170/QM170 Chipset SATA Controller [AHCI Mode]",
              "vendor" : "Intel Corporation",
              "physid" : "17",
              "businfo" : "pci@0000:00:17.0",
              "logicalname" : "scsi3",
              "version" : "31",
              "width" : 32,
              "clock" : 66000000,
              "configuration" : {
                "driver" : "ahci",
                "latency" : "0"
              },
              "capabilities" : {
                "sata" : true,
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "ahci_1.0" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing",
                "emulated" : "Emulated device"
              }                {
                  "id" : "disk",
                  "class" : "disk",
                  "claimed" : true,
                  "handle" : "GUID:5b6f3452-01b9-4f4d-88ba-cbe69f35c43d",
                  "description" : "ATA Disk",
                  "product" : "WDC WDS120G2G0B-",
                  "vendor" : "Western Digital",
                  "physid" : "0.0.0",
                  "businfo" : "scsi@3:0.0.0",
                  "logicalname" : "/dev/sda",
                  "dev" : "8:0",
                  "version" : "0000",
                  "serial" : "192234805463",
                  "units" : "bytes",
                  "size" : 120040980480,
                  "configuration" : {
                    "ansiversion" : "5",
                    "guid" : "5b6f3452-01b9-4f4d-88ba-cbe69f35c43d",
                    "logicalsectorsize" : "512",
                    "sectorsize" : "512"
                  },
                  "capabilities" : {
                    "gpt-1.00" : "GUID Partition Table version 1.00",
                    "partitioned" : "Partitioned disk",
                    "partitioned:gpt" : "GUID partition table"
                  }                    {
                      "id" : "volume:0",
                      "class" : "volume",
                      "handle" : "GUID:780b924d-e22e-4892-b3da-bb6b4c5309cd",
                      "description" : "Windows FAT volume",
                      "vendor" : "mkfs.fat",
                      "physid" : "1",
                      "businfo" : "scsi@3:0.0.0,1",
                      "version" : "FAT32",
                      "serial" : "63e0-3c5e",
                      "size" : 535805952,
                      "capacity" : 536870400,
                      "configuration" : {
                        "FATs" : "2",
                        "filesystem" : "fat",
                        "name" : "EFI System Partition"
                      },
                      "capabilities" : {
                        "boot" : "Contains boot code",
                        "fat" : "Windows FAT",
                        "initialized" : "initialized volume"
                      }
                    },
                    {
                      "id" : "volume:1",
                      "class" : "volume",
                      "claimed" : true,
                      "handle" : "GUID:fc04387c-90e1-4d0f-b7e2-f53f6dc7e20e",
                      "description" : "EXT4 volume",
                      "vendor" : "Linux",
                      "physid" : "2",
                      "businfo" : "scsi@3:0.0.0,2",
                      "logicalname" : ["/dev/sda2", "/"],
                      "dev" : "8:2",
                      "version" : "1.0",
                      "serial" : "343689b9-3c28-4923-bf85-cd35c992c493",
                      "size" : 119502012416,
                      "configuration" : {
                        "created" : "2020-04-02 15:18:54",
                        "filesystem" : "ext4",
                        "lastmountpoint" : "/",
                        "modified" : "2020-06-17 10:24:00",
                        "mount.fstype" : "ext4",
                        "mount.options" : "rw,relatime,errors=remount-ro",
                        "mounted" : "2020-06-17 10:24:01",
                        "state" : "mounted"
                      },
                      "capabilities" : {
                        "journaled" : true,
                        "extended_attributes" : "Extended Attributes",
                        "large_files" : "4GB+ files",
                        "huge_files" : "16TB+ files",
                        "dir_nlink" : "directories with 65000+ subdirs",
                        "recover" : "needs recovery",
                        "64bit" : "64bit filesystem",
                        "extents" : "extent-based allocation",
                        "ext4" : true,
                        "ext2" : "EXT2/EXT3",
                        "initialized" : "initialized volume"
                      }
                    },

                },

            },
            {
              "id" : "pci:0",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCIBUS:0000:01",
              "description" : "PCI bridge",
              "product" : "100 Series/C230 Series Chipset Family PCI Express Root Port #1",
              "vendor" : "Intel Corporation",
              "physid" : "1c",
              "businfo" : "pci@0000:00:1c.0",
              "version" : "f1",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "pcieport"
              },
              "capabilities" : {
                "pci" : true,
                "pciexpress" : "PCI Express",
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "normal_decode" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "pci:1",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCIBUS:0000:02",
              "description" : "PCI bridge",
              "product" : "100 Series/C230 Series Chipset Family PCI Express Root Port #2",
              "vendor" : "Intel Corporation",
              "physid" : "1c.1",
              "businfo" : "pci@0000:00:1c.1",
              "version" : "f1",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "pcieport"
              },
              "capabilities" : {
                "pci" : true,
                "pciexpress" : "PCI Express",
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "normal_decode" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }                {
                  "id" : "generic",
                  "class" : "bus",
                  "claimed" : true,
                  "handle" : "PCI:0000:02:00.0",
                  "description" : "MMC Host",
                  "product" : "SD/MMC Card Reader Controller",
                  "vendor" : "O2 Micro, Inc.",
                  "physid" : "0",
                  "businfo" : "pci@0000:02:00.0",
                  "logicalname" : "mmc0",
                  "version" : "01",
                  "width" : 32,
                  "clock" : 33000000,
                  "configuration" : {
                    "driver" : "sdhci-pci",
                    "latency" : "0"
                  },
                  "capabilities" : {
                    "pm" : "Power Management",
                    "msi" : "Message Signalled Interrupts",
                    "pciexpress" : "PCI Express",
                    "bus_master" : "bus mastering",
                    "cap_list" : "PCI capabilities listing"
                  }
                },

            },
            {
              "id" : "pci:2",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCIBUS:0000:03",
              "description" : "PCI bridge",
              "product" : "100 Series/C230 Series Chipset Family PCI Express Root Port #3",
              "vendor" : "Intel Corporation",
              "physid" : "1c.2",
              "businfo" : "pci@0000:00:1c.2",
              "version" : "f1",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "pcieport"
              },
              "capabilities" : {
                "pci" : true,
                "pciexpress" : "PCI Express",
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "normal_decode" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }                {
                  "id" : "network",
                  "class" : "network",
                  "disabled" : true,
                  "claimed" : true,
                  "handle" : "PCI:0000:03:00.0",
                  "description" : "Wireless interface",
                  "product" : "Wireless 8260",
                  "vendor" : "Intel Corporation",
                  "physid" : "0",
                  "businfo" : "pci@0000:03:00.0",
                  "logicalname" : "wlp3s0",
                  "version" : "3a",
                  "serial" : "00:c2:c6:d8:a1:2b",
                  "width" : 64,
                  "clock" : 33000000,
                  "configuration" : {
                    "broadcast" : "yes",
                    "driver" : "iwlwifi",
                    "driverversion" : "5.3.0-59-generic",
                    "firmware" : "36.77d01142.0",
                    "latency" : "0",
                    "link" : "no",
                    "multicast" : "yes",
                    "wireless" : "IEEE 802.11"
                  },
                  "capabilities" : {
                    "pm" : "Power Management",
                    "msi" : "Message Signalled Interrupts",
                    "pciexpress" : "PCI Express",
                    "bus_master" : "bus mastering",
                    "cap_list" : "PCI capabilities listing",
                    "ethernet" : true,
                    "physical" : "Physical interface",
                    "wireless" : "Wireless-LAN"
                  }
                },

            },
            {
              "id" : "pci:3",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCIBUS:0000:04",
              "description" : "PCI bridge",
              "product" : "100 Series/C230 Series Chipset Family PCI Express Root Port #5",
              "vendor" : "Intel Corporation",
              "physid" : "1c.4",
              "businfo" : "pci@0000:00:1c.4",
              "version" : "f1",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "pcieport"
              },
              "capabilities" : {
                "pci" : true,
                "pciexpress" : "PCI Express",
                "msi" : "Message Signalled Interrupts",
                "pm" : "Power Management",
                "normal_decode" : true,
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "isa",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCI:0000:00:1f.0",
              "description" : "ISA bridge",
              "product" : "HM170 Chipset LPC/eSPI Controller",
              "vendor" : "Intel Corporation",
              "physid" : "1f",
              "businfo" : "pci@0000:00:1f.0",
              "version" : "31",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "latency" : "0"
              },
              "capabilities" : {
                "isa" : true,
                "bus_master" : "bus mastering"
              }
            },
            {
              "id" : "memory",
              "class" : "memory",
              "handle" : "PCI:0000:00:1f.2",
              "description" : "Memory controller",
              "product" : "100 Series/C230 Series Chipset Family Power Management Controller",
              "vendor" : "Intel Corporation",
              "physid" : "1f.2",
              "businfo" : "pci@0000:00:1f.2",
              "version" : "31",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "latency" : "0"
              }
            },
            {
              "id" : "multimedia",
              "class" : "multimedia",
              "claimed" : true,
              "handle" : "PCI:0000:00:1f.3",
              "description" : "Audio device",
              "product" : "100 Series/C230 Series Chipset Family HD Audio Controller",
              "vendor" : "Intel Corporation",
              "physid" : "1f.3",
              "businfo" : "pci@0000:00:1f.3",
              "version" : "31",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "snd_hda_intel",
                "latency" : "32"
              },
              "capabilities" : {
                "pm" : "Power Management",
                "msi" : "Message Signalled Interrupts",
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              }
            },
            {
              "id" : "serial",
              "class" : "bus",
              "claimed" : true,
              "handle" : "PCI:0000:00:1f.4",
              "description" : "SMBus",
              "product" : "100 Series/C230 Series Chipset Family SMBus",
              "vendor" : "Intel Corporation",
              "physid" : "1f.4",
              "businfo" : "pci@0000:00:1f.4",
              "version" : "31",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "i801_smbus",
                "latency" : "0"
              }
            },
            {
              "id" : "network",
              "class" : "network",
              "claimed" : true,
              "handle" : "PCI:0000:00:1f.6",
              "description" : "Ethernet interface",
              "product" : "Ethernet Connection (2) I219-LM",
              "vendor" : "Intel Corporation",
              "physid" : "1f.6",
              "businfo" : "pci@0000:00:1f.6",
              "logicalname" : "eno1",
              "version" : "31",
              "serial" : "00:1f:c6:9b:b8:fe",
              "units" : "bit/s",
              "size" : 1000000000,
              "capacity" : 1000000000,
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "autonegotiation" : "on",
                "broadcast" : "yes",
                "driver" : "e1000e",
                "driverversion" : "3.2.6-k",
                "duplex" : "full",
                "firmware" : "0.8-4",
                "ip" : "192.168.1.100",
                "latency" : "0",
                "link" : "yes",
                "multicast" : "yes",
                "port" : "twisted pair",
                "speed" : "1Gbit/s"
              },
              "capabilities" : {
                "pm" : "Power Management",
                "msi" : "Message Signalled Interrupts",
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing",
                "ethernet" : true,
                "physical" : "Physical interface",
                "tp" : "twisted pair",
                "10bt" : "10Mbit/s",
                "10bt-fd" : "10Mbit/s (full duplex)",
                "100bt" : "100Mbit/s",
                "100bt-fd" : "100Mbit/s (full duplex)",
                "1000bt-fd" : "1Gbit/s (full duplex)",
                "autonegotiation" : "Auto-negotiation"
              }
            },

        },
        {
          "id" : "pnp00:00",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "1",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:01",
          "class" : "generic",
          "claimed" : true,
          "product" : "PnP device NTN0530",
          "physid" : "2",
          "configuration" : {
            "driver" : "nuvoton-cir"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:02",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "3",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:03",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "4",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:04",
          "class" : "system",
          "claimed" : true,
          "product" : "AT Real-Time Clock",
          "physid" : "5",
          "configuration" : {
            "driver" : "rtc_cmos"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:05",
          "class" : "generic",
          "claimed" : true,
          "product" : "PnP device INT3f0d",
          "physid" : "6",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:06",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "7",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:07",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "8",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:08",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "9",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:09",
          "class" : "system",
          "claimed" : true,
          "product" : "Motherboard registers",
          "physid" : "a",
          "configuration" : {
            "driver" : "system"
          },
          "capabilities" : {
            "pnp" : true
          }
        },

    },

]

**Comment by nayefc** [comment]
@limbo127 That's the bug that I tried to address, which broke other JSON parsing. lshw will not work for all JSON outputs unless properly reworked.

**Comment by blackmennewstyle** [comment]
> @limbo127 That's the bug that I tried to address, which broke other JSON parsing. lshw will not work for all JSON outputs unless properly reworked.

Any update/ETA on this issue? GNU/Linux Debian has this json output syntax error bug since many many years, it will be great if this could be fixed once for all.

**Comment by jamshid** [comment]
I guess it's known that the standard debian:11 package for lshw does not show a version and has json formatting bugs on some hardware? This will never be fixed (rebuilt or upgraded) in debian:11?
```
$ docker run -ti debian:11 bash
# apt-get update && apt-get install -y lshw
Get:1 http://deb.debian.org/debian bullseye/main amd64 lshw amd64 02.18.85-0.7 [279 kB]
...
# lshw -version

# lshw -h
Hardware Lister (lshw) - 
usage: lshw [-format] [-options ...]
       lshw -version
       
	-version        print program version ()

format can be
...
```

**Pull request closed without merging**
